name: .NET Core
on: [push, pull_request]

jobs:
  build:
    if: contains(github.event.head_commit.message, '[ci]') || contains(github.event.head_commit.message, '[ci_linux]') || contains(github.event.head_commit.message, '[ci_windows]') || contains(github.event.head_commit.message, '[ci_mac]')
    strategy:
      matrix:
        operatingSystem: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        skip: [ true ]
        exclude:
        - operatingSystem: 'ubuntu-latest'
          skip: ${{fromJSON(!contains(github.event.head_commit.message, '[ci]') && !contains(github.event.head_commit.message, '[ci_linux]'))}}
        - operatingSystem: 'windows-latest'
          skip: ${{fromJSON(!contains(github.event.head_commit.message, '[ci]') && !contains(github.event.head_commit.message, '[ci_windows]'))}}
        - operatingSystem: 'macos-latest'
          skip: ${{fromJSON(!contains(github.event.head_commit.message, '[ci]') && !contains(github.event.head_commit.message, '[ci_mac]'))}}
    runs-on: ${{ matrix.operatingSystem }}
    timeout-minutes: 10

    steps:
    - run: Helloe World2
