on: push
jobs:
    job2:
        runs-on: ${{ matrix.operatingSystem }}
        strategy:
            matrix:
              operatingSystem: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
              skip: ['true']
              exclude:
                - operatingSystem: 'ubuntu-latest'
                  skip: ${{!contains(github.event.head_commit.message, '[ci]') && !contains(github.event.head_commit.message, '[ci_linux]')}}
                - operatingSystem: 'windows-latest'
                  skip: ${{!contains(github.event.head_commit.message, '[ci]') && !contains(github.event.head_commit.message, '[ci_windows]')}}
                - operatingSystem: 'macos-latest'
                  skip: ${{!contains(github.event.head_commit.message, '[ci]') && !contains(github.event.head_commit.message, '[ci_mac]')}}

        steps:
        - name: hehe
          run: |
            echo other: ${{matrix.operatingSystem}}
