name: .NET Core
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        operatingSystem: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        skip: [ true ]
        exclude:
        - operatingSystem: 'ubuntu-latest'
          skip: true
        - operatingSystem: 'windows-latest'
          skip: true
        - operatingSystem: 'macos-latest'
          skip: true
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - run: echo Hello World2
