on: push
jobs:
    job2:
        runs-on: ${{ matrix.operatingSystem }}
        strategy:
            matrix:
              operatingSystem: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
              skip: [ true ]
              exclude:
                - operatingSystem: 'ubuntu-latest'
                  skip: true
                - operatingSystem: 'windows-latest'
                  skip: false
                - operatingSystem: 'macos-latest'
                  skip: true

        steps:
        - name: hehe
          run: |
            echo other: ${{!contains(github.event.head_commit.message, '[ci]') && !contains(github.event.head_commit.message, '[ci_linux]')}}
